[package]
name = "Tephra"
version = "0.1.0"
edition = "2021"
authors = ["Henry Steinmetz <matteo.steinmetz@t-online.de>"]
license = "MIT"

[dependencies]
eframe = "0.29.1"
serde = { version = "1.0.215", features = ["derive"] }
tempfile = "3.14.0"
