import { VerticalBox, HorizontalBox } from "std-widgets.slint";

import { SearchContainer } from "./search/main.slint";
import { MainContainer } from "./main/main.slint";


export component MainWindow inherits Window {
  title: "Tephra";
  HorizontalBox {
    alignment: space-around;
  
    VerticalBox {
      width: 100%;
      height: 100%;
      alignment: space-around;
      
      SearchContainer {
        
      }
      
      MainContainer {

      }
    }
  }
}
