import { HorizontalBox, LineEdit } from "std-widgets.slint";

enum SearchType {
  Filename,
  Tag
}

struct SearchRecommendation {
  text: string,
  type: SearchType
}

struct Query {
  tags: [string],
  input: string
}

export component SearchContainer inherits Rectangle {
  border-radius: 1rem;
  width: 95%;
  height: 25%;

  in-out property <[string]> tags;

  //callback search(Query);
  //callback fetch_recommendatins(Query) -> [SearchRecommendation];

  HorizontalBox {
    spacing: 0.5rem;

    LineEdit {
      placeholder-text: "Type to search";

      accepted(input) => {
        //root.search({tags: tags, input: input});
      }

      edited(input) => {
        //root.fetch-recommendatins({ tags: tags, input: input });
      }
    }

  }
}
